"""EDA 09 - do MSOA11s keep their accessibility rank between the DfT 2011 and 2014 series?

2011 = DfT Accessibility Statistics (older method, 2001 LSOA codes moved to MSOA11); 2014 = DfT Journey Time Statistics (new method).
The series are NOT comparable in levels (DfT), so only rank-based agreement is assessed: Pearson and Spearman correlations,
quartile agreement (quartiles formed within each year's England MSOA11 distribution), and agreement with the straight-line
distance to the nearest 2004 town centre and with population density. Higher = less accessible throughout.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from eda_common import *  # noqa: F401,F403
from report_utils import md_table

log = get_logger("eda_09_accessibility_2011_vs_2014")
style()
OUT = out_dir(EDA_DIR, "accessibility")
SVC = ["employment", "primary_school", "secondary_school", "further_education", "gp", "hospital", "food_store", "town_centre"]


def quart(s: pd.Series) -> np.ndarray:
    return pd.qcut(s.rank(method="first"), 4, labels=[1, 2, 3, 4]).astype(int).values


def main() -> int:
    a11 = pd.read_parquet(PROJECT_ROOT / "data" / "interim" / "geography_crosswalks" / "msoa11_accessibility2011.parquet").set_index("msoa11cd")
    b = load_baseline().set_index("msoa11cd")
    a14 = b.loc[a11.index]
    pairs = []
    for m, ml in (("pt", "public transport/walk"), ("car", "car")):
        for s in SVC:
            pairs.append((f"{s} ({ml})", a11[f"access2011_{s}_{m}_min"], a14[f"access_{s}_{m}_min_2014"], m))
        pairs.append((f"key-services composite, 8 services ({ml})", a11[f"access2011_keyservices_{m}_min"], a14[f"access_keyservices_{m}_min_2014"], m))
        pairs.append((f"key-services composite, 7 services excl. town centres ({ml})", a11[f"access2011_keyservices7_{m}_min"],
                      a14[[f"access_{s}_{m}_min_2014" for s in SVC if s != "town_centre"]].mean(axis=1), m))
    rows = []
    for lab, x, y, m in pairs:
        qx, qy = quart(x), quart(y)
        rows.append({"measure": lab, "mode": m, "mean_2011": x.mean(), "mean_2014": y.mean(), "pearson": x.corr(y), "spearman": x.corr(y, method="spearman"),
                     "share_same_quartile": float((qx == qy).mean()), "share_moving_2plus_quartiles": float((abs(qx - qy) >= 2).mean()),
                     "top_quartile_2011_still_top": float((qy[qx == 4] == 4).mean()), "bottom_quartile_2011_still_bottom": float((qy[qx == 1] == 1).mean())})
    res = pd.DataFrame(rows)
    res.to_csv(OUT / "accessibility_2011_vs_2014_persistence.csv", index=False)

    # how does each year's composite relate to distance to town centre and density
    rel = []
    for lab, s in (("2011 composite, public transport", a11["access2011_keyservices_pt_min"]), ("2014 composite, public transport", a14["access_keyservices_pt_min_2014"]),
                   ("2011 composite, car", a11["access2011_keyservices_car_min"]), ("2014 composite, car", a14["access_keyservices_car_min_2014"])):
        rel.append({"measure": lab, "pearson_with_dist_town_centre": s.corr(a14["dist_town_centre_km"]), "spearman_with_dist_town_centre": s.corr(a14["dist_town_centre_km"], method="spearman"),
                    "pearson_with_log_density": s.corr(a14["log_population_density_2011"]), "spearman_with_log_density": s.corr(a14["log_population_density_2011"], method="spearman")})
    rel = pd.DataFrame(rel)
    rel.to_csv(OUT / "accessibility_2011_2014_relation_to_distance_and_density.csv", index=False)
    log.info("2011 vs 2014:\n" + res[["measure", "pearson", "spearman", "share_same_quartile", "share_moving_2plus_quartiles"]].round(3).to_string(index=False))

    fig, axes = plt.subplots(1, 3, figsize=(16, 4.8))
    for ax, (lab, x, y) in zip(axes, [("composite, public transport/walk", a11["access2011_keyservices_pt_min"], a14["access_keyservices_pt_min_2014"]),
                                      ("composite, car", a11["access2011_keyservices_car_min"], a14["access_keyservices_car_min_2014"]),
                                      ("town centre, public transport/walk", a11["access2011_town_centre_pt_min"], a14["access_town_centre_pt_min_2014"])]):
        ax.hexbin(x.rank(pct=True), y.rank(pct=True), gridsize=40, cmap="Blues", mincnt=1)
        ax.plot([0, 1], [0, 1], "r", lw=.7)
        ax.set_title(f"{lab}\nSpearman {x.corr(y, method='spearman'):.2f}", fontsize=9)
        ax.set_xlabel("rank percentile, 2011 series")
        ax.set_ylabel("rank percentile, 2014 series")
    savefig(fig, OUT / "rank_rank_2011_vs_2014_accessibility.png")

    L = ["# Accessibility: 2011 series vs 2014 series (MSOA11)\n",
         "Generated by `src/eda/eda_09_accessibility_2011_vs_2014.py`. 2011 = DfT Accessibility Statistics (older method; 2001 LSOA codes moved to MSOA11 with the ONS best-fit lookup; "
         "split or irregular LSOAs get an equal split of their weight, about 2.4% of employment weight). 2014 = DfT Journey Time Statistics. DfT states the two series are not comparable in levels, "
         "so only ranks are compared. Higher = less accessible. The 2011 employment centre definition is >= 500 jobs (2014: 500-4,999 jobs).\n",
         md_table(res, nd=3), "", "## Relation of each year's composite to distance to town centre and to density\n", md_table(rel, nd=3), "",
         "Figure: `rank_rank_2011_vs_2014_accessibility.png`.\n"]
    (OUT / "ACCESSIBILITY_2011_VS_2014.md").write_text("\n".join(L))
    return 0


if __name__ == "__main__":
    sys.exit(main())
