"""EDA 07 - assemble outputs/eda/EDA_REPORT.md from the tables written by eda_01 ... eda_06.
Every number in the report is read from a CSV; nothing is typed in by hand."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from eda_common import *  # noqa: F401,F403
from report_utils import md_table

log = get_logger("eda_07_report")
T = EDA_DIR / "tables"


def rd(p: str, **kw) -> pd.DataFrame:
    return pd.read_csv(T / p, **kw)


def main() -> int:
    L = []
    A = L.append
    A("# Exploratory data analysis: England MSOA11 x year panel\n")
    A("Generated by `src/eda/eda_07_report.py` from the tables in `outputs/eda/tables/`. Scripts: `src/eda/eda_01 ... eda_06`.")
    A("The report states what each analysis found; it does not draw policy conclusions. Units are given where they matter.\n")
    A("**Reading notes.** The outcome is `log_median_ppsqm`, the log of the median **nominal** price per m2 in an MSOA-year "
      "(not CPIH-deflated). The treatment is new-build completions per 1,000 baseline (2011) households. Main sample = 2016-2023; "
      "the full panel is 2012-2023. Quartile 4 of deprivation = most deprived; income quartile 1 = poorest.\n")

    # 1
    A("## 1. Data structure and quality (eda_01)\n")
    A(md_table(rd("01_panel_balance.csv")) + "\n")
    miss = rd("01_missingness.csv")
    A("Columns with missing values (all others are complete). `nb_lead*`, `nb_lag1`, `d_log_price*` are derived in memory at analysis "
      "time (they are missing at the ends of each MSOA's series by construction); the new-build floor-area columns are missing where "
      "an MSOA-year has no new-builds.\n")
    A(md_table(miss.rename(columns={"Unnamed: 0": "variable"})) + "\n")
    A("### Within and between variance\n")
    A("Within-MSOA = variation over time inside an MSOA (what fixed effects use); between = differences between MSOA averages.\n")
    vb = rd("01_within_between_variance.csv")
    A(md_table(vb[vb["sample"] == "main_2016_2023"][["variable", "overall_sd", "between_sd", "within_sd", "within_share_of_variance"]]) + "\n")
    A("### Distributions\n")
    dist = rd("01_distribution_summary.csv")
    keyv = ["log_median_ppsqm", "median_ppsqm", "newbuilds_per_1000", "newbuilds_lag1_per_1000", "sale_count", "d_log_price"]
    A(md_table(dist[dist.variable.isin(keyv)][["variable", "mean", "sd", "min", "median", "p99", "max", "skew", "excess_kurtosis", "share_zero"]]) + "\n")
    A("Histograms of every numeric variable: `outputs/eda/figures/distributions/hist_all_variables_p*.png`; QQ plots: `qq_key_variables.png`.\n")
    A("### Treatment by year and its upper tail\n")
    A(md_table(rd("01_treatment_zero_share_by_year.csv")) + "\n")
    A(md_table(rd("01_treatment_upper_tail.csv")) + "\n")
    A("Largest MSOA-year construction rates (new-builds per 1,000 households):\n")
    A(md_table(rd("01_treatment_top25_outliers.csv"), max_rows=10) + "\n")
    A("The total number of new-builds in 2023 is much lower than in 2022 (see table above); completions in the most recent year are less complete.\n")
    A("### Transaction counts\n")
    A(md_table(rd("01_sale_count_distribution.csv")) + "\n")
    A(md_table(rd("01_sale_count_threshold_exposure.csv")) + "\n")
    A("Standardised mean difference in baseline characteristics, MSOA-years below the threshold vs the rest:\n")
    lc = rd("01_low_sales_characteristics.csv")
    A(md_table(lc.pivot(index="characteristic", columns="threshold", values="std_mean_diff").reset_index()) + "\n")
    A("Figure: `outputs/eda/figures/sale_count_profile.png`.\n")

    # 2
    A("## 2. Correlations (eda_02)\n")
    A("Moderators (MSOA level, Pearson):\n")
    A(md_table(pd.read_csv(T / "correlations" / "moderators_pearson.csv", index_col=0).round(3).reset_index().rename(columns={"index": ""}), nd=3) + "\n")
    A("Moderators (Spearman):\n")
    A(md_table(pd.read_csv(T / "correlations" / "moderators_spearman.csv", index_col=0).round(3).reset_index().rename(columns={"index": ""}), nd=3) + "\n")
    A("Partial correlations (each pair holding the other four constant):\n")
    A(md_table(pd.read_csv(T / "correlations" / "moderators_partial_correlations.csv", index_col=0).round(3).reset_index().rename(columns={"index": ""}), nd=3) + "\n")
    A("Correlation of the outcome with the treatment at different levels (main sample). `two_way_within` removes MSOA and year means, "
      "the variation a two-way fixed-effects model uses:\n")
    A(md_table(pd.read_csv(T / "correlations" / "treatment_outcome_correlation_by_level.csv").rename(columns={"Unnamed: 0": "treatment variable"}), nd=3) + "\n")
    A("Cross-sectional correlation of the treatment with the outcome by year:\n")
    A(md_table(pd.read_csv(T / "correlations" / "treatment_outcome_correlation_by_year.csv"), nd=3) + "\n")
    A("Full matrices: `outputs/eda/tables/correlations/` (pooled Pearson/Spearman for every numeric variable, ranked pairs, "
      "between/within/two-way-within, baseline). Heatmaps and scatter matrices: `outputs/eda/figures/correlations/`.\n")

    # 3
    A("## 3. Trends over time (eda_03)\n")
    A(md_table(rd("trends/03_national_series.csv").reset_index().round(3)) + "\n")
    A("Share of the within-MSOA variance explained by common components (year, region x year, LAD x year means):\n")
    A(md_table(rd("trends/03_common_shock_variance_shares.csv"), nd=3) + "\n")
    A("Within-MSOA autocorrelation:\n")
    ac = rd("trends/03_within_autocorrelation.csv")
    A(md_table(ac.pivot(index="lag", columns="variable", values="within_autocorrelation").reset_index(), nd=3) + "\n")
    A(md_table(rd("trends/03_zero_persistence.csv"), nd=3) + "\n")
    A(md_table(rd("trends/03_beta_convergence.csv"), nd=4) + "\n")
    A("Figures: `outputs/eda/figures/trends/` (national series, paths by moderator quartile and by region, heatmaps, maps).\n")

    # 4
    A("## 4. PCA (eda_04)\n")
    A("Six baseline moderators:\n")
    A(md_table(pd.read_csv(T / "pca" / "04_eigenvalues_six_moderators.csv"), nd=3) + "\n")
    A(md_table(pd.read_csv(T / "pca" / "04_loadings_six_moderators.csv").rename(columns={"Unnamed: 0": "variable"}), nd=3) + "\n")
    A("Four primary moderators:\n")
    A(md_table(pd.read_csv(T / "pca" / "04_eigenvalues_four_primary_moderators.csv"), nd=3) + "\n")
    A(md_table(pd.read_csv(T / "pca" / "04_loadings_four_primary_moderators.csv").rename(columns={"Unnamed: 0": "variable"}), nd=3) + "\n")
    A("All baseline socioeconomic variables, first five components:\n")
    A(md_table(pd.read_csv(T / "pca" / "04_eigenvalues_all_baseline.csv").head(5), nd=3) + "\n")
    A("Price paths (6,791 x 12 matrix), share of variance by component:\n")
    pv = pd.read_csv(T / "pca" / "04_price_path_pca_variance.csv")
    A(md_table(pv.pivot_table(index="component", columns=["series", "preprocessing"], values="share_variance").reset_index(), nd=3) + "\n")
    A("Bai-Ng information criteria (number of factors with the smallest value is selected):\n")
    bn = pd.read_csv(T / "pca" / "04_bai_ng_number_of_factors.csv")
    A(md_table(bn[["series", "k_factors", "IC_p1", "IC_p2", "IC_p3"]], nd=3) + "\n")
    sel = bn.loc[bn.groupby("series")["IC_p2"].idxmin(), ["series", "k_factors"]]
    A("Number of factors minimising IC_p2: " + "; ".join(f"{r.series}: {r.k_factors}" for r in sel.itertuples()) + ".\n")
    A("Figures: `outputs/eda/figures/pca/`.\n")

    # 5
    A("## 5. Stationarity and cross-sectional dependence (eda_05)\n")
    A("Implementation check by simulation (N = 2,000): rejection rates at the 5% level. For HT, the random-walk row is the size; "
      "for Hadri, the iid row is the size. Hadri is not robust to serial correlation, so it rejects AR(0.5) series by construction.\n")
    A(md_table(rd("tests/05_simulation_validation.csv"), nd=3) + "\n")
    A("Panel stationarity tests on the real data (HT: H0 = unit root; HTtrend: with unit-specific trends; Hadri: H0 = stationary):\n")
    st = rd("tests/05_stationarity_tests.csv")
    A(md_table(st[["sample", "series", "cross_section_means_removed", "N", "T_obs", "HT_rho", "HT_p(H0 unit root)", "HTtrend_rho",
                   "HTtrend_p(H0 unit root)", "Hadri_p(H0 stationary)"]], nd=4) + "\n")
    A("Fisher-type combination of per-MSOA ADF tests (low power at T = 8-12):\n")
    A(md_table(rd("tests/05_stationarity_fisher_adf.csv"), nd=3) + "\n")
    A("Pesaran CD test and average pairwise correlations after removing successive common components (main sample):\n")
    cd = rd("tests/05_cross_sectional_dependence.csv")
    A(md_table(cd[cd["sample"] == "main_2016_2023"][["series", "effects_removed", "N", "CD", "CD_p", "mean_pairwise_corr_all",
                                                  "mean_abs_pairwise_corr_all", "mean_corr_neighbours"]], nd=4) + "\n")
    A("In LADs with fewer than 10 MSOAs the LAD x year demeaning forces negative residual correlation, so the LAD x year rows use only "
      "larger LADs.\n")

    # 6
    A("## 6. Spatial structure (eda_06)\n")
    A(md_table(rd("spatial/06_neighbour_structure.csv"), nd=2) + "\n")
    mo = rd("spatial/06_morans_I.csv")
    A("Global Moran's I (queen contiguity, 999 permutations), by variable (mean over years where yearly):\n")
    A(md_table(mo.groupby("variable").agg(mean_I=("morans_I", "mean"), min_I=("morans_I", "min"), max_I=("morans_I", "max"),
                                          max_p=("p_sim", "max")).reset_index(), nd=3) + "\n")
    A(md_table(rd("spatial/06_treatment_own_vs_neighbour_correlation.csv"), nd=3) + "\n")
    A("LISA cluster counts: `outputs/eda/tables/spatial/06_lisa_cluster_counts.csv`; maps: `outputs/eda/figures/spatial/lisa_maps.png`.\n")

    A("## Output index\n")
    A("- Tables: `outputs/eda/tables/` (subfolders `correlations`, `trends`, `pca`, `tests`, `spatial`)\n"
      "- Figures: `outputs/eda/figures/` (subfolders `distributions`, `correlations`, `trends`, `pca`, `spatial`)\n"
      "- Neighbour weights and MSOA11 boundaries: `data/raw/geography/msoa11_boundaries/MSOA11_BGC_England.geojson` (see `config/source_manifest.csv`)\n")
    (EDA_DIR / "EDA_REPORT.md").write_text("\n".join(L))
    log.info(f"Wrote {EDA_DIR / 'EDA_REPORT.md'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
