"""M08 - assemble outputs/models/MODEL_LAB_REPORT.md from the tables written by m01 ... m07.
Every number is read from a CSV. The report describes results and units; it makes no policy statements."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from model_common import *  # noqa: F401,F403
from report_utils import md_table

log = get_logger("m08_report")
T = MODEL_DIR / "tables"


def rd(p: str, **kw) -> pd.DataFrame:
    return pd.read_csv(T / p, **kw)


def main() -> int:
    L = []
    A = L.append
    A("# Baseline specification lab: results\n")
    A("Generated by `src/models/m08_report.py` from `outputs/models/tables/`. Scripts `src/models/m01 ... m07`. "
      "These are diagnostic regressions used to choose a specification, not final results.\n")
    A("**Set-up.** Outcome: log median nominal price per m2. Treatment x: new-builds per 1,000 baseline households completed in the previous year "
      "(`newbuilds_lag1_per_1000`). Moderators are England-wide z-scores. Sample: main sample 2016-2023, LADs with at least 2 MSOAs "
      "(54,312 MSOA-years, 6,789 MSOAs, 294 LADs). Standard errors clustered by LAD unless stated. M3 = MSOA + year FE; M6 = MSOA + LAD x year FE.\n")
    lad = rd("m01_fe_ladder_coefficients.csv")
    m3 = lad[(lad.model == "M3") & (lad.cluster == "lad")].iloc[0]
    A("**How to read a coefficient.** " + units_sentence(float(m3.coef)) + f" One standard deviation of x is about {m3.pct_change_per_1sd_x:.3f}% "
      "on the same scale (`pct_change_per_1sd_x`: the effect of a one-SD increase in x, 17.6 new-builds per 1,000 households). "
      "For an interaction, the coefficient on x*z is the change in the per-unit coefficient for an MSOA one England-wide standard deviation "
      "higher on that moderator; multiplied by 100 it gives the change in the percentage effect per additional new-build per 1,000 households, "
      "in percentage points.\n")

    A("## 1. Fixed-effects ladder (m01)\n")
    A("Coefficient on x without controls, as the fixed effects are added:\n")
    A(md_table(lad[lad.cluster == "lad"][["model", "label", "coef", "se", "p", "n_obs", "r2_within", "pct_change_per_1sd_x"]], nd=6) + "\n")
    A("Same coefficients with standard errors clustered by MSOA:\n")
    A(md_table(lad[lad.cluster == "msoa"][["model", "coef", "se", "p"]], nd=6) + "\n")
    A("Tests of the fixed effects (classical F-tests assume iid errors; the cluster-robust year-effects Wald test is the last row):\n")
    A(md_table(rd("m01_fixed_effects_f_tests.csv"), nd=3) + "\n")
    A("Mundlak test (the coefficient on `x_msoa_mean` is the between-minus-within difference; the cluster-robust version of the Hausman test):\n")
    A(md_table(rd("m01_mundlak_test.csv")[["term", "coef", "se", "t", "p"]], nd=6) + "\n")
    A("Residual diagnostics. Wooldridge serial-correlation test (under no serial correlation the first-differenced residual's autocorrelation is -0.5):\n")
    A(md_table(rd("m01_wooldridge_serial_correlation.csv"), nd=4) + "\n")
    A("Breusch-Pagan test of heteroskedasticity (regressors: 1/sale_count and x), and residual variance by sale-count decile:\n")
    A(md_table(rd("m01_heteroskedasticity_bp.csv"), nd=3) + "\n")
    rv = rd("m01_residual_variance_by_sales_decile.csv")
    A(md_table(rv.pivot(index="mean_sales", columns="model", values="resid_variance").reset_index(), nd=5) + "\n")
    A("Cross-sectional dependence of the residuals (Pesaran CD, average pairwise correlation, correlation among neighbours):\n")
    A(md_table(rd("m01_residual_cross_sectional_dependence.csv"), nd=4) + "\n")
    mo = rd("m01_residual_morans_I_by_year.csv")
    A("Moran's I of the residuals (mean over years): " + "; ".join(
        f"{m}: {g.morans_I.mean():.3f}" for m, g in mo.groupby("model")) + ".\n")
    A("Share of the residual variance that sits in group means:\n")
    A(md_table(rd("m01_residual_variance_by_group.csv").pivot(index="grouping", columns="model", values="share_of_residual_variance_in_group_means").reset_index(), nd=4) + "\n")
    A("Sensitivity of the coefficient to the sample and the measure of treatment (units differ by row; `treatment_variable` names the regressor):\n")
    sens = rd("m01_treatment_definition_sensitivity.csv")
    A(md_table(sens[["model", "label", "treatment_variable", "coef", "se", "p", "n_obs"]], nd=6) + "\n")

    A("## 2. Transaction counts: thresholds and weights (m02)\n")
    th = rd("m02_sales_threshold_weights_coefficients.csv")
    A(md_table(th[["model", "label", "coef", "se", "p", "n_obs", "r2_within"]], nd=6) + "\n")
    A("Share of MSOA-years retained by moderator quartile when the minimum-sales threshold is 30:\n")
    comp = rd("m02_sample_composition_by_quartile.csv")
    c30 = comp[comp.restriction == "sales >= 30"].pivot(index="quartile", columns="moderator", values="share_of_cells_retained").reset_index()
    A(md_table(c30, nd=3) + "\n")
    A(md_table(rd("m02_variance_vs_inverse_sales.csv"), nd=5) + "\n")

    A("## 3. Moderators (m03)\n")
    A(f"{len(rd('m03_specification_sets.csv'))} moderator sets x 2 fixed-effects structures x 2 control variants were estimated; "
      "all are listed in `m03_moderator_models_coefficients.csv` and the registry. Interaction coefficients are in log points per unit of x, per 1 SD of the moderator. "
      "`p_holm` is the Holm-adjusted p-value within the family (same FE structure, same control variant, same number of moderators in the set).\n")
    res = rd("m03_moderator_models_coefficients.csv")
    for fe in ("M3", "M6"):
        for ctl in (False, True):
            tag = "zyear" if ctl else "plain"
            A(f"### {fe}, {'with moderator x year controls' if ctl else 'interactions only'}\n")
            for sname in ("income+deprivation+social_rent+density", "all_six", "pc1+pc2"):
                s = res[res.spec_id == f"{fe}_{tag}_{sname}"][["term", "coef", "se", "p", "p_holm_within_family"]]
                A(f"Set `{sname}`:\n")
                A(md_table(s, nd=6) + "\n")
    A("Joint test that all interaction coefficients are zero (LAD-clustered Wald), main sets:\n")
    jt = rd("m03_moderator_models_joint_tests.csv")
    A(md_table(jt[jt.set.isin(["income+deprivation+social_rent+density", "all_six", "pc1+pc2"])][
        ["fe", "year_controls", "set", "wald_chi2", "q", "p_chi2", "r2_within"]], nd=4) + "\n")
    A("Each interaction alone vs in the joint models (no moderator x year controls):\n")
    aj = rd("m03_alone_vs_joint.csv")
    A(md_table(aj[~aj.year_controls][["fe", "moderator", "coef_alone", "se_alone", "coef_with_four_primary", "se_with_four_primary",
                                      "coef_with_all_six", "se_with_all_six"]], nd=6) + "\n")
    A("Variance inflation factors of the regressors after the within transformation:\n")
    A(md_table(rd("m03_interaction_vif.csv").pivot_table(index=["set", "regressor"], columns="fe", values="VIF").reset_index(), nd=2) + "\n")
    A("Marginal effects of x at z = -1, 0, +1 (single-moderator models, M3 and M6): `m03_marginal_effects.csv`, figure `outputs/models/figures/m03_marginal_effects_single_moderators.png`.\n")

    A("## 4. Endogeneity checks (m04)\n")
    A("Leads and lags of construction (coefficients; `N_lead*` = construction in later years, `N_lag*` = in earlier years). Samples: A uses no completions "
      "after 2022; C includes a lead that reaches 2023, when completions are under-counted:\n")
    ll = rd("m04_leads_lags_coefficients.csv")
    A(md_table(ll[["fe", "sample", "term", "coef", "se", "p", "n_obs"]], nd=6) + "\n")
    A("Joint test that the lead coefficients are zero:\n")
    A(md_table(rd("m04_leads_joint_tests.csv")[["fe", "sample", "leads_tested", "wald_chi2", "q", "p_chi2", "n_obs"]], nd=4) + "\n")
    A("Sum of the coefficients on t to t-3:\n")
    A(md_table(rd("m04_cumulative_lag_effect.csv"), nd=6) + "\n")
    A("Reverse direction (outcome: construction per 1,000 households in year t; regressors: log price growth in t-1, t-2):\n")
    A(md_table(rd("m04_reverse_direction.csv")[["fe", "spec", "term", "coef", "se", "p"]], nd=4) + "\n")
    A("Pre-period (2012-2015 price growth vs 2016-2023 construction):\n")
    A(md_table(rd("m04_pre_period_correlation.csv"), nd=4) + "\n")
    A(md_table(rd("m04_pre_period_regression.csv")[["spec_id", "term", "coef", "se", "p"]], nd=4) + "\n")
    A(md_table(rd("m04_pre_growth_by_construction_quartile.csv"), nd=4) + "\n")
    A("Event study, top-quartile-construction MSOAs vs others (reference year 2015):\n")
    es = rd("m04_pretrend_event_study_coefficients.csv")
    A(md_table(es.pivot(index="year", columns="fe", values="coef").reset_index(), nd=4) + "\n")
    A("Figures: `outputs/models/figures/m04_leads_lags_event_study.png`, `m04_pretrend_event_study.png`.\n")

    A("## 5. Spillovers (m05)\n")
    A("Neighbouring-construction variables are persisted by `src/13b_prepare_spatial_spillovers.py` (queen contiguity primary; 5 km and distance-decay robustness) and "
      "read from the final panel. Neighbouring prices are not used as a regressor. All exposures are new builds per 1,000 households (lag 1).\n")
    A("Reproduction check: the preliminary results (own only; own + mean of neighbours' rates; own + cross-LAD mean), rebuilt from the persisted variables, "
      "equal the earlier saved results (`m05_reproduction_check.csv`).\n")
    A(md_table(rd("m05_neighbour_variable_info.csv"), nd=3) + "\n")
    A("Preliminary specifications (neighbour term = mean of neighbours' rates):\n")
    A(md_table(rd("m05_spillover_baseline.csv")[["fe", "spec", "term", "coef", "se", "p"]], nd=6) + "\n")
    A("Four-moderator model with and without the neighbour variable (joint test of the interactions):\n")
    A(md_table(rd("m05_spillover_with_moderators_joint.csv"), nd=4) + "\n")
    A("Specification comparison on one common sample (MSOA-years where every exposure is defined; MSOAs with no population-weighted centroid within 5 km are dropped). "
      "Coefficients are per one extra completion per 1,000 households, in log points; interaction uses the focal MSOA's England-wide income z-score:\n")
    comp = rd("m05_spillover_specification_comparison.csv")
    A(md_table(comp[["fe", "spec", "term", "coef", "se", "p", "n_obs"]], nd=6) + "\n")
    A(md_table(rd("m05_spillover_specification_comparison_joint_tests.csv")[["fe", "spec", "wald_chi2", "q", "p_chi2"]], nd=4) + "\n")
    A("These are exploratory associations, not causal estimates (see `docs/spillover_exposure_methodology.md`).\n")

    A("## 6. Standard errors and clustering (m06)\n")
    A(md_table(rd("m06_baseline_se_by_clustering.csv")[["fe", "vcov", "coef", "se", "p", "n_clusters", "se_ratio_to_iid"]], nd=6) + "\n")
    A("(`lad_and_year` is two-way clustering; its smaller cluster dimension is the 8 years.)\n")
    A("Joint test of the four interactions by clustering level:\n")
    A(md_table(rd("m06_moderator_joint_by_clustering.csv"), nd=4) + "\n")
    A("Wild-cluster bootstrap (LAD clusters, 999 Rademacher draws, null imposed) against the asymptotic LAD-clustered p-value:\n")
    A(md_table(rd("m06_wild_cluster_bootstrap.csv")[["fe", "term", "t_cluster", "p_wild_cluster_bootstrap", "p_asymptotic_lad_cluster"]], nd=4) + "\n")

    A("## 7. Variation available to an instrument (m07, mechanical)\n")
    A(md_table(rd("m07_variation_surviving_fixed_effects.csv"), nd=4) + "\n")
    A("See `docs/iv_literature_note.md`. The funding-indicator check from the plan is not run because the policy registry is not part of this build; "
      "the LAD x year row above describes the same algebra for any LAD-year variable.\n")

    reg = pd.concat([pd.read_csv(p) for p in sorted(T.glob("spec_registry_m*.csv")) if p.stat().st_size > 5])
    reg.to_csv(T / "spec_registry_ALL.csv", index=False)
    A("## 8. Specification registry\n")
    A(f"{len(reg)} regressions were run across m01-m07 (`spec_registry_ALL.csv`); {int((reg.status != 'ok').sum())} failed. "
      "Because many specifications are compared, p-values from a single specification should be read with that count in mind; the Holm "
      "adjustment in section 3 covers the interaction tests within each family only.\n")
    A("## 9. Notes on this build\n")
    A("- The outcome is built from nominal prices; year effects absorb the common nominal trend.\n"
      "- Completions in 2023 are incomplete (UPRN geography matching and EPC lodgement lag), which affects leads that reach 2023.\n"
      "- Moderators are fixed at baseline; their main effects are absorbed by MSOA fixed effects.\n"
      "- Place-based funding variables are not included.\n")
    (MODEL_DIR / "MODEL_LAB_REPORT.md").write_text("\n".join(L))
    log.info(f"Wrote {MODEL_DIR / 'MODEL_LAB_REPORT.md'} ({len(reg)} specs in registry)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
